# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift_For_RESTAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift_For_RESTAPI
pod 'Alamofire', '~> 5.4'
end
